force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <description>Items to complete during your day.</description>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Todo is completed.</description>
    <inlineHelpText>Todo is completed.</inlineHelpText>
    <label>Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Created_On__c.field-meta.xml
<CustomField>
    <fullName>Created_On__c</fullName>
    <description>Date the task was created on.</description>
    <inlineHelpText>Date the task was created on.</inlineHelpText>
    <label>Created On</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A description of what needs to get done.</description>
    <inlineHelpText>A description of what needs to get done.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TodoHandler.cls
public with sharing class TodoHandler {
  @AuraEnabled(cacheable=true)
  public static List<Todo__c> getTodoTasks() {
    return [
      SELECT Id, Description__c, Completed__c, Created_On__c
      FROM Todo__c
      WHERE CreatedById = :UserInfo.getUserId() AND Completed__c = FALSE
      ORDER BY Created_On__c
    ];
  }
  @AuraEnabled(cacheable=true)
  public static List<Todo__c> getCompletedTasks() {
    return [
      SELECT Id, Description__c, Completed__c, Created_On__c
      FROM Todo__c
      WHERE CreatedById = :UserInfo.getUserId() AND Completed__c = TRUE
      ORDER BY Created_On__c
    ];
  }
  @AuraEnabled
  public static void completeTodoTask(String taskId) {
    Todo__c task = new Todo__c();
    task.Id = taskId;
    task.Completed__c = true;
    update task;
  }
  @AuraEnabled
  public static void returnTodoTask(String taskId) {
    Todo__c task = new Todo__c();
    task.Id = taskId;
    task.Completed__c = false;
    update task;
  }
}